### ISSUE TITLE
Failed to Grab Tab List

### ISSUE THREAD

**Issue by dabreadman** [briansd9/exile-diary#74] opened 2020-07-18 19:33 UTC
I entered my account name as shown on pathofexile.com, and extracted the POESSID in cookies, but it is saying that it failed to get tab list for my account even though the tab list was shown to me.

Error:
![image](https://user-images.githubusercontent.com/43485369/87860503-ddcef900-c935-11ea-815c-2d3e8ed67b25.png)
Tab list it retrieved:
![image](https://user-images.githubusercontent.com/43485369/87860509-ede6d880-c935-11ea-9a4c-8dd6d32ffd20.png)

**Comment by briansd9** [comment] 2020-07-19 01:33
Hi, thanks very much for the report, I've been having trouble tracking down this bug.

In your log file `%appdata%\exile-diary\log.txt` there should be a line "Failed to get tab list" followed by an error message. Can you post the message here?

**Comment by dabreadman** [comment] 2020-07-19 11:08
[log.txt](https://github.com/briansd9/exile-diary/files/4943591/log.txt)

I'm selecting the flicker character if that information helps

**Comment by briansd9** [comment] 2020-07-19 11:37
Got it, thanks... some follow-up questions 

- Does the "Failed to get tab list" error show up every time you go to the settings page?
- Even though the error pops up, your tabs are still displayed, right?
- Do you have a [unique item tab](https://pathofexile.gamepedia.com/Unique_Collection_Tab)?

**Comment by dabreadman** [comment] 2020-07-19 11:40
Does the "Failed to get tab list" error show up every time you go to the settings page?
>No, only when I try to setup stash tabs for net worth.
Even though the error pops up, your tabs are still displayed, right?
>No, it doesn't
Net worth
![image](https://user-images.githubusercontent.com/43485369/87873871-efa7af00-c9bc-11ea-82e5-c7cede8e944d.png)
Stats
![image](https://user-images.githubusercontent.com/43485369/87873874-fa624400-c9bc-11ea-9e2a-b7e51f75e64f.png)
Do you have a unique item tab?
>No

**Comment by dabreadman** [comment] 2020-07-19 11:53
After running a few maps with Dairy on, it starts showing the net worth

**Comment by briansd9** [comment] 2020-07-19 11:55
I have found the cause of the error, will be fixed in the next update. Net worth will also be retrieved immediately after setting up, instead of needing to run a map first.

Thanks very much for your help!

**Comment by dabreadman** [comment] 2020-07-19 11:56
Welcome

**Closed** 2020-07-19 11:56 UTC
